# This file created by conda-build 3.20.3
# meta.yaml template originally from:
# /home/mnguyen/FFPolish/conda, last modified Thu Oct 29 16:56:11 2020
# ------------------------------------------------

package:
    name: ffpolish
    version: 0.1.0
source:
    fn: ffpolish.0.1.0.tar.gz
    md5: 8bf9597b1fdfa6ff1fdd58c664c0ab36
    url: https://github.com/morinlab/FFPolish/archive/v0.1.0.tar.gz
build:
    number: '4'
    string: py37_4
requirements:
    build:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 1_gnu
        - ca-certificates 2020.6.20 hecda079_0
        - certifi 2020.6.20 py37he5f6b98_2
        - ld_impl_linux-64 2.35 h769bd43_9
        - libffi 3.2.1 he1b5a44_1007
        - libgcc-ng 9.3.0 h5dbcf3e_17
        - libgomp 9.3.0 h5dbcf3e_17
        - libstdcxx-ng 9.3.0 h2ae2ef3_17
        - ncurses 6.2 he1b5a44_2
        - openssl 1.1.1h h516909a_0
        - pip 20.2.4 py_0
        - python 3.11.4 h955ad1f_0
        - python_abi 3.7 1_cp37m
        - readline 8.0 he28a2e2_2
        - setuptools 49.6.0 py37he5f6b98_2
        - sqlite 3.33.0 h4cf870e_1
        - tk 8.6.10 hed695b0_1
        - wheel 0.35.1 pyh9f0ad1d_0
        - xz 5.2.5 h516909a_1
        - zlib 1.2.11 h516909a_1010
    run:
        - bam-readcount=1.0.1
        - bedops=2.4.39
        - convert_zero_one_based=0.0.1
        - numpy=1.19.2
        - pandas=1.1.3
        - pysam=0.16.0
        - python>=3.11
        - scikit-learn=0.23.2
        - tqdm=4.50.2
        - vaex
test:
    commands:
        - ffpolish --help
about:
    home: https://github.com/morinlab/FFPolish
    license: MIT
    summary: FFPolish filters artifacts from FFPE variant calls
extra:
    copy_test_source_files: true
    final: true
